version: '3.1'

networks:
  climatempo_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

services:
  frontend:
    container_name: climatempo-frontend
    build: ./app/frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    environment:
      - REACT_APP_JWT_SECRET=clima_top_secret_tempo
      - REACT_APP_BASE_ENDPOINT=http://localhost:3001
    depends_on:
      - backend
    networks:
      - climatempo_network
    external_links:
      - backend

  backend:
    container_name: climatempo-backend
    build: ./app/backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    environment:
      - JWT_SECRET=clima_top_secret_tempo
      - PORT=3001
    restart: always
    networks:
      - climatempo_network
    external_links:
      - frontend
