version: '3.1'

networks:
  climatempo_network:
    driver:
      bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

services:
  frontend:
    container_name: climatempo-frontend
    build: ./app/frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    depends_on:
      - backend
    networks:
      - climatempo_network
    external_links:
      - backend
